# importing libraries

In [16]:
import numpy as np 
import pandas as pd


# coverting data to Data Frame

In [18]:
data=pd.DataFrame({"bias":[1,1,1,1,1,1,1,1],
    "x1":[60,62,67,70,71,72,75,78],
      "x2":[22,25,24,20,15,14,14,11],
      "y":[0,0,0,0,1,1,1,1]})
print(data)
print(data.shape)

   bias  x1  x2  y
0     1  60  22  0
1     1  62  25  0
2     1  67  24  0
3     1  70  20  0
4     1  71  15  1
5     1  72  14  1
6     1  75  14  1
7     1  78  11  1
(8, 4)


# initializing theeta"s

In [76]:
theta=np.random.randint(0,2,3) # intializing theeta's
print(theta)

[1 0 1]


# computing hypothesis

In [78]:
z=theta[0]*data["bias"]+theta[1]*data["x1"]+theta[2]*data["x2"]
print(z)

0    23
1    26
2    25
3    21
4    16
5    15
6    15
7    12
dtype: int64


# adding my Z or hypothesis in my Data Frame

In [81]:
data["z/hypothesis"]=theta[0]*data["bias"]+theta[1]*data["x1"]+theta[2]*data["x2"]
print(data)

   bias  x1  x2  y  z/hypothesis  sigmoid  cost
0     1  60  22  0            23      1.0   inf
1     1  62  25  0            26      1.0   inf
2     1  67  24  0            25      1.0   inf
3     1  70  20  0            21      1.0   inf
4     1  71  15  1            16      1.0   inf
5     1  72  14  1            15      1.0   inf
6     1  75  14  1            15      1.0   inf
7     1  78  11  1            12      1.0   inf


# computing sigmoid function

In [83]:
def sigmoid(data):
    s=1+np.exp(-data["z/hypothesis"])
    sigmoid=1/s
    return sigmoid  

# checking wheather my sigmoid function is correct or not 

In [85]:
sig=sigmoid(data)
print(sig)

0    1.000000
1    1.000000
2    1.000000
3    1.000000
4    1.000000
5    1.000000
6    1.000000
7    0.999994
Name: z/hypothesis, dtype: float64


# Also adding my sigmoid in my Data Frame

In [87]:
data["sigmoid"]=sigmoid(data)
print(data)

   bias  x1  x2  y  z/hypothesis   sigmoid  cost
0     1  60  22  0            23  1.000000   inf
1     1  62  25  0            26  1.000000   inf
2     1  67  24  0            25  1.000000   inf
3     1  70  20  0            21  1.000000   inf
4     1  71  15  1            16  1.000000   inf
5     1  72  14  1            15  1.000000   inf
6     1  75  14  1            15  1.000000   inf
7     1  78  11  1            12  0.999994   inf


# Calculating cost function Using Binary Cross Entropy

In [124]:
m=8
def cost_function(data):
    for i in range(m):
        a=1/m
        b=data["y"]*(np.log(data["sigmoid"]))
        c=(1-data["y"])+(np.log(1-data["sigmoid"]))
        result=b+c
        cost=-a*result
    return cost


# Computing Cost Function 

In [126]:
cost=cost_function(data)
print(cost)

0    2.750000
1    3.125002
2    2.999999
3    2.500000
4    2.000000
5    1.875000
6    1.875000
7    1.500002
dtype: float64


# Now Adding my cost function in Data Frame

In [93]:
data["cost"]=cost_function(data)
print(data)

   bias  x1  x2  y  z/hypothesis   sigmoid      cost
0     1  60  22  0            23  1.000000  2.750000
1     1  62  25  0            26  1.000000  3.125002
2     1  67  24  0            25  1.000000  2.999999
3     1  70  20  0            21  1.000000  2.500000
4     1  71  15  1            16  1.000000  2.000000
5     1  72  14  1            15  1.000000  1.875000
6     1  75  14  1            15  1.000000  1.875000
7     1  78  11  1            12  0.999994  1.500002


# Calculating Gradient Descent

In [143]:
m=8
alpha=0.02
def gradient_Descent(data):
        grad_0=np.sum((data["z/hypothesis"]-data["y"])*data["bias"])/m
        grad_1=np.sum((data["z/hypothesis"]-data["y"])*data["x1"])/m
        grad_2=np.sum((data["z/hypothesis"]-data["y"])*data["x2"])/m
        theta[0]=theta[0]-alpha*(grad_0)
        theta[1]=theta[1]-alpha*(grad_1)
        theta[2]=theta[2]-alpha*(grad_2)
        
        return theta
        
    

In [159]:
data.head()

bias  x1  x2  y  z/hypothesis  sigmoid      cost
0     1  60  22  0            23      1.0  2.750000
1     1  62  25  0            26      1.0  3.125002
2     1  67  24  0            25      1.0  2.999999
3     1  70  20  0            21      1.0  2.500000
4     1  71  15  1            16      1.0  2.000000

# computing gradient descent

In [153]:
gradient=gradient_Descent(data)
iteration=10
for i in range(iteration):
    gradient=gradient_Descent(data)
    print((gradient))
    
         

[   0 -625 -175]
[   0 -650 -182]
[   0 -675 -189]
[   0 -700 -196]
[   0 -725 -203]
[   0 -750 -210]
[   0 -775 -217]
[   0 -800 -224]
[   0 -825 -231]
[   0 -850 -238]


# so updated theta's are 

In [155]:
print(gradient)

[   0 -850 -238]
